# Generated by Django 4.1.7 on 2023-02-24 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('issue_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('maturity_date', models.DateField()),
                ('total_expected_interest_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_identifier', models.CharField(max_length=15)),
                ('reference_date', models.DateField()),
                ('type', models.CharField(choices=[('funding', 'Funding'), ('repayment', 'Repayment')], max_length=10)),
                ('amount', models.FloatField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='backend.loan')),
            ],
        ),
    ]
