# Generated by Django 4.1.7 on 2023-02-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=10, unique=True)),
                ('issue_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('rating', models.IntegerField()),
                ('maturity_date', models.DateField()),
                ('total_expected_interes_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField()),
                ('type', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('loan_identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='backend.loan')),
            ],
        ),
    ]
