# Generated by Django 4.1.7 on 2023-02-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='type',
            field=models.CharField(choices=[('funding', 'Funding'), ('repayment', 'Repayment')], max_length=10),
        ),
    ]
