# Generated by Django 4.1.7 on 2023-02-14 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_cashflow_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='total_expected_interes_amount',
            new_name='total_expected_interest_amount',
        ),
        migrations.AlterField(
            model_name='loan',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
